name: Replan Delivery Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Fix gradlew permissions
        run: chmod +x ./gradlew

      - name: Start SUT in test mode
        run: java -jar ./artifacts/app-ibank.jar -P:profile=test &
        shell: bash

      - name: Run tests
        run: ./gradlew test -Dselenide.headless=true
        shell: bash